{% set name = "ipython-sql" %}
{% set version = "0.3.9" %}
{% set sha256= "7187f6371f38b89d8fb63c2c7c4233d9000fb53b460dae79e4a359df366cc3ed" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: ipython-sql-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - prettytable
    - ipython >=1.0  # [not win]
    - ipython >=1.0  # [win and not py35]
    - ipython >=1.0,<5  # [win and py35]
    - sqlparse
    - six

  run:
    - python
    - prettytable
    - ipython >=1.0  # [not win]
    - ipython >=1.0  # [win and not py35]
    - ipython >=1.0,<5  # [win and py35]
    - sqlalchemy >=0.6.7
    - sqlparse
    - six

test:
  imports:
    - sql

about:
  home: https://pypi.python.org/pypi/ipython-sql
  license: MIT
  #TODO catherinedevlin/ipython-sql#58 
  #license_file: <LICENSE>
  summary: 'RDBMS access via IPython'

extra:
  recipe-maintainers:
    - sodre
