{% set version = "0.3.8" %}
{% set md5 = "89080b1bd4f383006a07164673af5d0d" %}

package:
  name: ipython-sql
  version: {{ version }}

source:
  fn: ipython-sql-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/4b/4d/d62e65d8f501a305f45ff0b5a317163b742ea0c61e01ae85595ef5d1a54f/ipython-sql-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - prettytable
    - ipython >=1.0  # [not win]
    - ipython >=1.0  # [win and not py35]
    - ipython >=1.0,<5  # [win and py35]
    - sqlparse
    - six

  run:
    - python
    - prettytable
    - ipython >=1.0  # [not win]
    - ipython >=1.0  # [win and not py35]
    - ipython >=1.0,<5  # [win and py35]
    - sqlalchemy >=0.6.7
    - sqlparse
    - six

test:
  imports:
    - sql

about:
  home: https://pypi.python.org/pypi/ipython-sql
  license: MIT
  license_file: LICENSE
  summary: 'RDBMS access via IPython'

extra:
  recipe-maintainers:
    - sodre
