travis:
  secure:
    BINSTAR_TOKEN: aii9xBT5VCrqsLozezfKAy4Vg7c7Hsql1HVXGld5QSHA47cBxyJLoJNzLnUd6IuaP3obtvo5F0WiYHF8tLwudAxOXdepKJZTGAJGAcOPH/751Yec3ERpIu5EaNKT+TFmp6nyWsDSjzXENrhrlX1YAWnQQ5uL3Ft0dDLl4fkmhwxclJy3a//KTPFnnulAqcatFTTZgEQa0ODYEtJHo6k3D1Fan4a8HBz7tqVvY8sHlpNuL9sG/gybEAmReUVi+O9BkmYZtYYYjKYeSjKR4+CF3qVXePsM6XIZIwRUnHSI9KIIz3VSz41q4Xai0vS219wQLFfxsQk4nyKO/zJOoWuGJjt9cntvNIeZF07draivH7ThQZ9N9trV1I3lSNdE/CjbRrwiKQUJGUSFt4QL+dqEAQa0y/y6jjry7Ef4dOsSnwgbGQV2aH+q3x44Qlxx5u0WusHbo9JRb+e5yz4Y1NaXhhxwgYQtLijo5ZKMl7KhPnEktzyWpx5pl8fGzEOSLEU8OBy3rm461rf6GynMORQv0/59/Xs7Wzi1thRmEije25xwhZU8ahOL1EZPtfRmO3dZFMAH+/UNIHofwv7+VreaoE6cRBkZh7l52PkmISDjhygD2jTNHkm8RqFzvKbG9J8X2aPEfXJFYcRuWjOwnhFXzv4W6QY36TMUDwIMkkjEvgw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
