travis:
  secure:
    BINSTAR_TOKEN: oQR9b6VZLG8wKbq4lKkYNIBAZ3NySL8Q6SRm5pWSrU4jhXokkhC7RyArOzNqHQ00DeloTlU2fcCgSo/Ppdt4Sbl2wYUiL7ym6EGebJU4OCI+Ma9OczLiPh9ESj2JF13ZssjqcjJOWaQlexpry5ZubZ9V/iZqJMdUWl3LIqqxGnWumkhI2d6S65dtee/ChyyUVuiJSa8DyIQbiMK+1TvFZZe789pKZtURqbtPNUDi8s2Z7sqxXybO9EWl3ovm9edAudM/STkvIU3MVPr03I1jmeHuNizprfBias4f4ESFnSmG+TJy3mVX9Nofbf785597Y0BuMnwZC2kPb6QtXf2bgSv7BspQMOfCX1eXnI7XfxEyObX1eeNu2z8tZXBhLUG6/tf2jiYJuWUXyNQP4cIf3uLEh6sv1ogbvE1N/a/v4yHBBsFIMJKiTW8LdQOf+3Se+nwwPArSFWHpQZm9pNenAGYjZuh+HE9kmr5ta/0OhYBNvl7GW5HQ1NvsZB6MsVOUbM+gcw0AnwES+8xztwFzNTUk2KDs2IvSKE4rvERmDpksrvXZzTsU1Xg2xNJICHbGVvWqN9PMVggNxBF/2IQyc/5D91pQijY6ribPACx6uYyYxjVtoWJBtOdmkL8Kxkz3/D9kal9HJjj6BRUihR+X8NMG5IrT5EpESXCXgWGTb84=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
